### ISSUE TITLE
Improvement Suggestion: Seperating checks into different files to maintain easily.

### ISSUE THREAD

**Issue by f** [arasatasaygin/is.js#10]
Seperating checks to the folder and file structures and compiling them may make the project easier to maintain and more modular.

```
checks/
    type/
         - array.js
         - arguments.js
         ...
    env/
        - android.js
        - ipad.js
        ...
```

It will make the codebase easier for someone to add new checks without breaking the core.

**Comment by f** [comment]
Proposal:

```js
// hello.js
module.exports = {
    name: 'hello',
    checker: function(value) {
        return value === 'hello';
    },
    supports: ['not']
};
```

It may export to:

```js
is.hello('hello'); // true;
is.not.hello('hello'); // false;
```

**Comment by arasatasaygin** [comment]
It looks like a good structure.
The whole library is pretty small -at the moment- and most of the methods are one-liners. So module per method may become an overkill.

What do you think about modularizing the check groups? Like maintaining and providing methods under:
- type
- env
- str

**Comment by oldboyxx** [comment]
I think it's fine as it is, let's not complicate only because we can.

**Comment by arasatasaygin** [comment]
Most of the feedbacks were about modularizing the library but I think I like it the way it is -simple- right now as you said @oldboyxx 
We'll see the other opinions and decide upon it.

**Comment by davidhund** [comment]
Personally I'd like to be able to create custom builds so 'modularizing the check groups' sounds like a great way to do this (without adding too much complexity)

**Comment by f** [comment]
> What do you think about modularizing the check groups?

It sounds like a good idea to me.

@oldboyxx
> I think it's fine as it is, let's not complicate only because we can.

I agree but it's not making it complex, it's making it maintainable and modular, like custom modules.

If I'm using this library in a NodeJS project, I wouldn't need the `env` checkers. I may want to customize it running something like

```
grunt build --exclude=env
```

**Comment by irthos** [comment]
+1 idea separating the core script from the types and giving the option to include sets or custom sets that match structure.

**Comment by blacksonic** [comment]
@f initial solution might be an overkill, but modularizing based on groups would increase readability. That way files can be kept around max. 100-200 lines. Everything above it is huge. Not mentioning the test file, nearly 3k lines.

**Comment by jdalton** [comment]
This likely won't happen at this time.
