### ISSUE TITLE
is.url does not accept valid characters (?, +, %) and allow white spaces

### ISSUE THREAD

**Issue by marqu3z** [arasatasaygin/is.js#106]
```
is.url("foo.com bar") // true
is.url("foo.com/something.php?foo=bar") // false
is.url("foo.com/something%20else.php") // false
is.url("foo.com/page.php?foo=one+two") // false
```

Is this a desired behaviour?

**Comment by fslone** [comment]
I'd like to see this fixed as well. I personally use the regex from @dperini for URL's but that returns false for any URL not prefixed with http/https/ftp so it would change the behavior of the library slightly. You can see that regex here:

https://gist.github.com/dperini/729294

If everyone would be in favor of using that regex I can make the change and write the test cases. Just let me know.

**Comment by marqu3z** [comment]
I was looking at the same gist.
The author made a comparison table here: https://mathiasbynens.be/demo/url-regex

**Comment by fslone** [comment]
yeah that's where I got it from :P

**Comment by dperini** [comment]
@fslone,
if there is no need to validate the protocol scheme (http/https/ftp) remove the following part:

    // protocol identifier
    "(?:(?:https?|ftp)://)" +
if there is no need to validate user/password (user:pass) remove the following part:

    // user:pass authentication
    "(?:\\S+(?::\\S*)?@)?" +

the entire IPV4 part could also be removed to shorten the regex and make it more efficient.

Thumbs up !

**Comment by dperini** [comment]
@fslone,
the protocol part could also be made optional instead of removing it:

    // protocol identifier
    "(?:(?:https?|ftp)://)?" +
by just adding a question mark after the grouping parenthesis.

**Comment by fslone** [comment]
@dperini thanks, you're the man. I'm going to make a few changes to the regex like Diego has recommended and I'll submit a pull request for this change shortly.
