### ISSUE TITLE
Can it  use in node.js?

### ISSUE THREAD

**Issue by JamesYYang** [arasatasaygin/is.js#11]
Can it  use in node.js?

**Comment by arasatasaygin** [comment]
Yes you can use it in Node.js @JamesYYang 
It's not in npm registry though. I'll let you know about it.

**Comment by ericrange** [comment]
+1

**Comment by voronianski** [comment]
+1 that's huge please publish latest version to npm

/cc @arasatasaygin

**Comment by arasatasaygin** [comment]
```
npm install is_js
```
@JamesYYang @ericrange @voronianski  I've just published to npm. Let me know if you have any problems.
Cheers.
