### ISSUE TITLE
Make is.js compatible with 'use strict'

### ISSUE THREAD

**Issue by callicles** [arasatasaygin/is.js#113]
The library is not using 'use strict' at the moment. As a consequence it breaks when concatenated with strict mode code. It could be nice to make it compatible, they are not many triggered errors (1)

[line 28](https://github.com/arasatasaygin/is.js/blob/7eb5cda78b4d08ec647ddd43b8eed8f74be18275/is.js#L28)
```js
    var root = this || global; // global is undefined
```
should become something like:

```js
    var root = (typeof global !== 'undefined' && (typeof window === 'undefined' || window === global.window)) ? global : window;
```

**Comment by andre487** [comment]
There is a reliable way to get the global object: https://gist.github.com/rauschma/1bff02da66472f555c75 It works even in workers.

**Comment by jdalton** [comment]
Your concatenation process shouldn't enforce modes on code it doesn't own. `is.js` is in its own IIFE so should otherwise be fine for concatenation.
