### ISSUE TITLE
is.ie() returning false in Internet Explorer 11

### ISSUE THREAD

**Issue by eriklharper** [arasatasaygin/is.js#115]
![is_ie returning false in ie11](https://cloud.githubusercontent.com/assets/821864/6948990/7203ede0-d866-11e4-9e0b-d59f9f002c00.jpg)

**Comment by eriklharper** [comment]
was able to detect IE 11 with this: `(window.ActiveXObject) && "ActiveXObject" in window` from here: http://stackoverflow.com/questions/21825157/internet-explorer-11-detection

**Comment by ryantemple** [comment]
have just updated pull request #80 to include this fix - can separate it out if needs be.
