### ISSUE TITLE
isUTC

### ISSUE THREAD

**Issue by ericrange** [arasatasaygin/is.js#12]
hey, in my project i need this everytime. do you think it would fit in your lib? :)
```
isUTC: function(UTC) {
            var now = new Date();
            if (UTC >= new Date(now.getTime() + now.getTimezoneOffset() * 60000))
                return false;
            else
                return true;
        }
```

**Comment by arasatasaygin** [comment]
Thanks @ericrange It might become handy. Noted it.
What others think? Is there anybody needs this check?

**Comment by ericrange** [comment]
no... utc is valid if its between 0 and the utc of NOW! should not be negativ value and etc^^

**Comment by ericrange** [comment]
actually... utc is always valid if its between 0 and X... mmhh :(
what i need is if the utc ever existed. you know what i mean? :D
the best way would be
```
is.past(UTC)
```
if "my function" then true, else false

**Comment by ericrange** [comment]
its maybe toooo specific for your lib :(
but datetime operations especially with utc is very important in my business

**Comment by arasatasaygin** [comment]
What do you mean by 'if the utc ever existed'?

**Comment by ericrange** [comment]
if the utc is in the past... the utc (number) existed :D

**Comment by arasatasaygin** [comment]
Do you want a comparison to check whether the client’s local time is past or ahead UTC?

Some clarification:
Let's take 10:00 UTC.
For example local time for Istanbul is +2 UTC (12:00) and local time for New York is -5 UTC (5:00)
```javascript
isPastUTC(local_time_from_istanbul);
=> true
isPastUTC(local_time_from_new_york);
=> false
```
Is this what you’re asking? It's a little bit tricky check. But generally speaking:
UTC checks can be handy for lots of us.
Thanks for the suggestions.

**Comment by ericrange** [comment]
yes this is what i want! :)

**Comment by ericrange** [comment]
sorry for the description... im a little bit language disabled^^

**Comment by arasatasaygin** [comment]
Don't worry @ericrange 
My English is pretty poor too :) Noted a UTC check method. Thanks.
I'll let you know when it's published.

**Comment by gurel** [comment]
You can add an is.inrange function and convert the date checks into timestamps for speed and memory improvements

**Comment by jdalton** [comment]
Thanks!

We'll keep an eye on [the popularity of the request](https://github.com/arasatasaygin/is.js/blob/master/CONTRIBUTING.md#feature-requests).
