### ISSUE TITLE
Support for `is.browser`, `is.node`? (Will put in pr if there is)

### ISSUE THREAD

**Issue by cmpolis** [arasatasaygin/is.js#120]
This environment check is somewhat common in my codebases and I would imagine in other projects with browserify/isomorphic bits. Any opinions on `is.browser()` and `is.node()`?

Love this library - thanks everyone!

**Comment by codemonkey800** [comment]
One way we could add a check like this is to do a check for global variables that are particular to a browser and node, like `window` for browsers and `module` for node. 

I really like the check used in Underscore.js as stated in this [StackOverflow Question](http://goo.gl/ypkwMU). I'd do a pull request, but I'm not sure how I'd add a unit test for checking the browser. If anyone can do that, this would be an awesome feature.

**Comment by jdalton** [comment]
Thanks!

We'll keep an eye on [the popularity of the request](https://github.com/arasatasaygin/is.js/blob/master/CONTRIBUTING.md#feature-requests).
