### ISSUE TITLE
while use is.not.url() to match the following url, the page can't response

### ISSUE THREAD

**Issue by searchworld** [arasatasaygin/is.js#121]
The url is "http://v.example.com/v_show/id_XOTM1MzA5NjA4.html?from=y1.2-2.4.2-1"
It seems taking too long to match. One core of CPU is running fully.
Dose it a bug?
At last I use: 
https://github.com/fslone/is.js/commit/30a89e7e5ca6b3c4cf99555a27605d8606888312

**Comment by arasatasaygin** [comment]
I think. Same link take too much time to match in my machine too @searchworld 
Thanks. I'll look for the cause.

**Comment by fslone** [comment]
I think pulling in #106 would fix a lot of these problems that keep popping up for the url regex

**Comment by arasatasaygin** [comment]
:+1: @fslone thanks again
