### ISSUE TITLE
decimal rule failed 

### ISSUE THREAD

**Issue by thetutlage** [arasatasaygin/is.js#122]
Indicative makes use to is.js in some rules and decimal rule fails at certain point.

Here is a reference to same
https://github.com/AdonisJs/indicative/issues/2

Also 

```javascript
is.decimal(10.0)
// returns false
```

**Comment by thetutlage** [comment]
Any Updates

**Comment by arasatasaygin** [comment]
Hey @thetutlage thanks for the heads up.
Isn't this the wanted behaviour or the nature of the language? When you wrote '10.0' to the browser console, it casts it to the '10' instead of '10.0'
