### ISSUE TITLE
why is.js require itself

### ISSUE THREAD

**Issue by lc60005457** [arasatasaygin/is.js#125]
why is.js require itself.

    if(typeof define === 'function' && define.amd) {
        // AMD. Register as an anonymous module.
        define(['is'], function(is) {
            // Also create a global in case some scripts
            // that are loaded still are looking for
            // a global even when an AMD loader is in use.
            return (root.is = factory(is));
        });
    } else if(typeof exports === 'object') {
        // Node. Does not work with strict CommonJS, but
        // only CommonJS-like enviroments that support module.exports,
        // like Node.
        module.exports = factory(require('is_js'));
    } else {
        // Browser globals (root is window)
        root.is = factory(root.is);
    }

**Comment by rubenspgcavalcante** [comment]
Related to https://github.com/arasatasaygin/is.js/issues/100, problems with circular dependency

**Comment by arasatasaygin** [comment]
This issue is resolved with https://github.com/arasatasaygin/is.js/pull/138
