### ISSUE TITLE
Accept String Input for number check?

### ISSUE THREAD

**Issue by dereklin** [arasatasaygin/is.js#127]
I want to check if a string is in integer or decimal format, is there a way to do this using is.js?

I am using jQuery first:

      if (jQuery.isNumeric(input)) {
        input = Number(input);
      }

And then use is.js:

      if (is.integer(input)) {
        ...
      } else if (is.decimal(input)) {
        ...
      }

**Comment by arasatasaygin** [comment]
Your approach is right.
is.js is not casting types. The 'is.decimal' or 'is.integer' checks the parameters type first and returns appropriate result if parameter is number.
