### ISSUE TITLE
Clarify isNull checking

### ISSUE THREAD

**Issue by havenchyk** [arasatasaygin/is.js#128]
Hi, 

Is there any reason to check the second expression here https://github.com/arasatasaygin/is.js/blob/master/is.js#L128?

```js
is.null = function(value) {
        return value === null || toString.call(value) === '[object Null]';
    };
```

Could anyone clarify, why is it needed ` toString.call(value) === '[object Null]`?
@arasatasaygin

**Comment by havenchyk** [comment]
@arasatasaygin I can make PR and remove this line. Could you just say, why this check is needed?

**Comment by arasatasaygin** [comment]
I think it's ok to delete that part, like you said @havenchyk
Waiting for the PR. Cheers.

**Comment by havenchyk** [comment]
@arasatasaygin great, I will, thanks for response. But what was the purpose to add this line? is it just copy/paste issue or something else?

**Comment by arasatasaygin** [comment]
Probably I thought the difference between null and
```javascript
var nullObject = Object.create(null);
```
But it doesn't make sense because stringified version of nullObject is [object Object] as well.
