### ISSUE TITLE
Ubuntu not being recognized as Linux

### ISSUE THREAD

**Issue by inad9300** [arasatasaygin/is.js#131]
Hi,

I think the OS needs some more checks to be determined accurately. In this particular case I've found that Ubuntu is not recognized as a GNU/Linux OS. The `navigator.appVersion` value is `"5.0 (X11)"`. Typical scripts that perform this task include a forth check to determine if the OS is Unix-like. You can see an example here: http://www.javascripter.net/faq/operatin.htm

**Comment by ironmaniiith** [comment]
@inad9300 , can you please tell which browser and version of ubuntu are you using..?

**Comment by inad9300** [comment]
It was quite a long ago, but it was most likely Chromium.

**Comment by ironmaniiith** [comment]
Unable to reproduce, closing this issue for now.
