### ISSUE TITLE
Revise implementation of module system

### ISSUE THREAD

**Issue by arasatasaygin** [arasatasaygin/is.js#132]
Current implementation has some issues:
https://github.com/arasatasaygin/is.js/issues/100
https://github.com/arasatasaygin/is.js/issues/125

**Comment by ryantemple** [comment]
#138 hopefully fixes this

**Comment by ironmaniiith** [comment]
@arasatasaygin 
When will you be back on this project. It seems quite interesting to me and I want to contribute in it.
Thanks.

**Comment by arasatasaygin** [comment]
Hey :)
Thanks for the support and patience. Closing this one thanks ti @ryantemple
