### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by rostacik** [arasatasaygin/is.js#137]
dear sir,
have you considered creating NuGet package for your library? it would be really helpful for .NET part of the world.

thx :+1: ,
d

**Comment by arasatasaygin** [comment]
Hey @rostacik 
Thanks for your interest and sorry for the late response. Right now, this library is on npm and bower and I'm not planning any other package manager. But of course you can fork, maintain your own copy and publish to your community.
Cheers.
