### ISSUE TITLE
Object Empty Function Needed

### ISSUE THREAD

**Issue by ralphievolt** [arasatasaygin/is.js#141]
I want to  check if my object like below is empty or not. How to do this using is.js?

is.ObjectEmpty({this: 'is', 'sample': 'test'});
=> false

is.ObjectEmpty({this: ' ', 'sample': ' '});
=> true

**Comment by ironmaniiith** [comment]
You can add this lines in the file is.js to accomplish this task.

```javascript
is.ObjectEmpty = function(obj) {
    for(var i in obj){
        if(obj[i]!=""){
            return false;
        }
    }
    return true;   
}

**Comment by jdalton** [comment]
Thanks!

We'll keep an eye on [the popularity of the request](https://github.com/arasatasaygin/is.js/blob/master/CONTRIBUTING.md#feature-requests).
