### ISSUE TITLE
Checker for plain objects

### ISSUE THREAD

**Issue by h2non** [arasatasaygin/is.js#142]
Instead of `is.object()`, it could be `is.plainObject()`. Useful when checking raw JavaScript objects which it's first prototype inherited chain is equal to `Object.prototype` and it's constructor is `Object`.

Here it is the implementation in lodash:
https://github.com/lodash/lodash/blob/3.10.0/lodash.src.js#L9076

**Comment by jdalton** [comment]
Dup of #37.
