### ISSUE TITLE
is.hexColor(213) returning true

### ISSUE THREAD

**Issue by reacher-lu** [arasatasaygin/is.js#151]
just like  

``` js
is.hexColor(213)
is.hexColor('123')
```
isn't color values ,but returning true.

**Comment by kinday** [comment]
This happens because it is a valid shorthand color value without `#`.

`213` → `#221133`
`'123'` → `#112233`

You can read about [shorthand hexademical form](https://en.wikipedia.org/wiki/Web_colors#Shorthand_hexadecimal_form) at Wikipedia

@arasatasaygin, looks like you may close this issue.
