### ISSUE TITLE
Way to use any and all with parameter accepting checks - Especially numeric.

### ISSUE THREAD

**Issue by kyletheninja** [arasatasaygin/is.js#155]
I see how it could complicate things to let checks that accept extra parameters use any and all.

However I think it would be really useful to say things like,

is.any.under([33, 45, 67], 50);
=>return true
is.all.under([33, 45, 67], 50);
=>return false

I think it would make the numeric checks much more useful.

**Comment by jdalton** [comment]
Thanks!

We'll keep an eye on [the popularity of the request](https://github.com/arasatasaygin/is.js/blob/master/CONTRIBUTING.md#feature-requests).
