### ISSUE TITLE
ip address validation not working

### ISSUE THREAD

**Issue by thetutlage** [arasatasaygin/is.js#156]
Ip address validation passes for any given letter

```javascript
console.log(is.ip('H'))
```

**Comment by ryantemple** [comment]
The regex for this seems to have been taken from this StackOverflow question:

http://stackoverflow.com/questions/23483855/javascript-regex-to-validate-ipv4-and-ipv6-address-no-hostnames

which itself appears to have come from a textbook. I'd suggest what needs to happen is the code for IP just runs the checks for IPv4 and IPv6 although I don't know if the performance may suffer as a result.  I might see if I can knock together a PR but I don't think the maintainer is actively managing this repo anymore.

**Comment by ryantemple** [comment]
Worth mentioning that the IPv6 validation has the same bug

**Comment by ryantemple** [comment]
I've added an explicit test for this in the PR.  You may want to fork your own version to incorporate this fix

**Comment by thetutlage** [comment]
Okay, let me check this
