### ISSUE TITLE
es6 import ? 

### ISSUE THREAD

**Issue by mydearxym** [arasatasaygin/is.js#158]
```js
import is from 'is_js'
```
cause error , any idea ?

**Comment by Nicolab** [comment]
+1

**Comment by austinmao** [comment]
+1

**Comment by kinday** [comment]
I can’t reproduce it. Could someone provide repo with test case if this issue still exists?

**Comment by alexbaumgertner** [comment]
@kinday I made one https://github.com/alexbaumgertner/is-es6-error
But... it not reproduced :persevere:

**Comment by kinday** [comment]
M’kay... I tried my best and I can’t reproduce this one neither with Node v0.12 nor babel v5.

@arasatasaygin, seems like this one need to be closed until anyone deliver test case or description of how to reproduce a problem.

**Comment by alexbaumgertner** [comment]
@mydearxym @Nicolab @austinmao can you reproduce the bug?
I tried https://github.com/arasatasaygin/is.js/issues/158#issuecomment-170060187 but seems like bug was gone...

**Comment by austinmao** [comment]
I will try this weekend and update this thread.

**Comment by alexbaumgertner** [comment]
@austinmao did you reproduce the bug?
I tried https://github.com/alexbaumgertner/is-es6-error but seems it's all ok.

**Comment by austinmao** [comment]
@alexbaumgertner Sorry for the late reply. I have just tested it and do not see this error anymore.

**Comment by alexbaumgertner** [comment]
@austinmao thanks!

@mydearxym seems like problem is gone.
Could you close the issue please?

**Comment by mydearxym** [comment]
@austinmao  sorry for my delay, it:s not issue anymore ..
