### ISSUE TITLE
IE10 - navigator.vendor not supported

### ISSUE THREAD

**Issue by photostu** [arasatasaygin/is.js#16]
Still trying to figure out pull requests, until then, my attempt to fix this:

line 523:
var vendor = 'navigator' in window && 'vendor' in navigator && navigator.vendor.toLowerCase() || '';

**Comment by arasatasaygin** [comment]
Thanks @photostu appreciate it.

**Comment by photostu** [comment]
No problem, thanks for the sweet library :)

**Comment by arasatasaygin** [comment]
:)

**Comment by photostu** [comment]
so, I attempted to do a PR, let me know if that helps :)

**Comment by arasatasaygin** [comment]
Merged pull request https://github.com/arasatasaygin/is.js/pull/17
