### ISSUE TITLE
Abandoned? 

### ISSUE THREAD

**Issue by shinzui** [arasatasaygin/is.js#160]
Is there any chance to make [JerryCauser's](https://github.com/JerryCauser/is.js) fork the official repo? It seems that this repo is abandoned.

**Comment by arasatasaygin** [comment]
Hey @shinzui ,
Thanks for your interest and sorry for the absence. I'll be back to this project fulltime as of January 2016 and definitely check forks and improvements.
Cheers.

**Comment by fslone** [comment]
@arasatasaygin definitely let me know when you're back to this project, submitted a couple PR's and would like to help out more when it's back running

**Comment by arasatasaygin** [comment]
Appreciate it @fslone Definitely I'll let you know.
