### ISSUE TITLE
Maybe add linters to the project?

### ISSUE THREAD

**Issue by andre487** [arasatasaygin/is.js#165]
Linters can be used for making code better and more beautiful. For example it can be: [ESLint](https://github.com/eslint/eslint) or [JSHint](https://github.com/jshint/jshint) for reporting code errors and issues and [JSCS](https://github.com/jscs-dev/node-jscs) for codestyle.

It can be placed in pre-commit hook with packages like [git-hooks.js](https://github.com/tarmolov/git-hooks-js)

**Comment by kinday** [comment]
ESLint is modular, thus it handles code style perfectly. Also [husky](https://github.com/typicode/husky) is simpler to use.

**Comment by jdalton** [comment]
Linters are fine. Feel free to send a PR for eslint.

**Comment by andre487** [comment]
Done: #205

**Comment by jdalton** [comment]
🙌
