### ISSUE TITLE
[Suggestion] Separate country validators from is.js

### ISSUE THREAD

**Issue by raphaklaus** [arasatasaygin/is.js#172]
Hello! First things first. I'd like to congratulate the team behind is.js, the library seems to be very consistent!

However, methods like ``is.caPostalCode`` are specific for countries. I guess with the growth of the library,could exist other useful methods like that, but for a developer from Italy, in 99% of cases it's not useful and is a weight more. 

I suggest break this into specific cultural libraries, like italy.is.js, china.is.js. This way is.js will retain only the universal validators.

If it's already on plan, sorry to be repetitious :smile:

**Comment by friedemannsommer** [comment]
+1

**Comment by jdalton** [comment]
Thanks!

We'll keep an eye on [the popularity of the request](https://github.com/arasatasaygin/is.js/blob/master/CONTRIBUTING.md#feature-requests).
