### ISSUE TITLE
There should be is.before(date, date) and is.after(date, date) functions.

### ISSUE THREAD

**Issue by felipedrumond** [arasatasaygin/is.js#174]
Although this is easy to check, 'is' could have these functions to make javascript more readable.

**Comment by arasatasaygin** [comment]
Hey @felipedrumond 
Thanks for the suggestion. You can compare native date objects like:
```
if (dateObj1 < dateObj2) { 
  // do your thingy
}
```
I think this is a more natural check, so I'm not planning to add these checks for this time.
Cheers
