### ISSUE TITLE
is.palindrome bug

### ISSUE THREAD

**Issue by gabbaca** [arasatasaygin/is.js#176]
The is.palindrome function is not working on all strings.  For example, the following string would work "madam" but this string would not "a santa at nasa".  Since you are just reversing the string and doing a comparison.

To fix this, one option would be to remove certain characters such as spaces and then do a comparison to that string:
// check if string
if(is.not.string(str)) { return false; }
// remove special chars
var newStringReplaced = str.replace(/[^A-Z0-9]/ig, "").toLowerCase();
// reverse new string
var newStringReversed = newStringReplaced.split('').reverse().join('');
// make comparison
return newStringReplaced === newStringReversed

**Comment by fslone** [comment]
@arasatasaygin are you planning on merging pull requests anytime soon? If so I'll take care of this and some of the other bugs

**Comment by gabbaca** [comment]
Thanks @fslone

**Comment by fslone** [comment]
@gabbaca The only problem is I don't think this is still being maintained.

**Comment by ironmaniiith** [comment]
@arasatasaygin , I think it would be good if you can give merging rights to some of the people are who really interested to take this project forward in case if you are not able to give time to this. What say.?

**Comment by fslone** [comment]
Agreed

**Comment by ironmaniiith** [comment]
@arasatasaygin , can you give a rough idea when will you be back to this project.?

**Comment by frugalcoder** [comment]
@gabbaca 
> To fix this, one option would be to remove certain characters such as spaces and then do a comparison to that string

I don't think we should. Palindrome should work the way it's working now. Why should we treat some characters differently for generic situations?

**Comment by ironmaniiith** [comment]
@frugalcoder .
This paragraph from wikipedia suggests that we should.
https://en.wikipedia.org/wiki/Palindrome#Sentences_and_phrases

**Comment by frugalcoder** [comment]
Oh. Didn't know that. I guess it is required then.
If nobody is working on this, then I can fix this issue.

**Comment by ironmaniiith** [comment]
You can try but the author, @arasatasaygin is busy right now. Once the project is live again, we can start the contribution.
In the meanwhile you can work your own improvement branch [like this](https://github.com/ironmaniiith/is.js/tree/improvement), which can help later on if you are really interested :smile: .

**Comment by jdalton** [comment]
Moved to #202.

**Comment by evdama** [comment]
I've forked and explained it here https://github.com/evdama/is.js/commit/ca79bba3614e988a82e7ac47e6d8a14c61d6e706
