### ISSUE TITLE
Extending is.js with with own checks

### ISSUE THREAD

**Issue by Grawl** [arasatasaygin/is.js#18]
I just listed your readme and realized that is not only a great pack of functions but a great API for a new ones. So maybe you will provide some extending function to create something like `is.myExtension…`?

**Comment by arasatasaygin** [comment]
Hi @Grawl 
What kinds of interfaces would become handy except 'not', 'all' and 'any'? Maybe we cam implement them to the library.

**Comment by Grawl** [comment]
I mean not an interfaces. I mean custom checks like `is.ruPostalCode(string)` or `is.transliterated(string)` to wrap all project checks into is.js API.

**Comment by arasatasaygin** [comment]
Oh, got it. Planning to provide custom checks for RegExps -> https://github.com/arasatasaygin/is.js/issues/15
Maybe we can add a custom check wrapper for the whole library. I would prefer other checks to be in the library though.

**Comment by Grawl** [comment]
Yep, I'm about exact this. Wrapper will be awesome for every developer.
