### ISSUE TITLE
Why is this project dead?

### ISSUE THREAD

**Issue by jt3k** [arasatasaygin/is.js#184]
Where is the owner, why not accept pullrequests?
Select a trusted person and give him rights to manage this project.

**Comment by ironmaniiith** [comment]
@arasatasaygin , I guess its a good project and a good number of people are using it.
It would be really nice if you can make it active or give someone merging rights.

**Comment by arasatasaygin** [comment]
Hey thanks for your interest. I'm on it https://github.com/arasatasaygin/is.js/issues/186
