### ISSUE TITLE
How about the browser compatibility?

### ISSUE THREAD

**Issue by youngwind** [arasatasaygin/is.js#185]
hi, I have read the document but did not find any declaration about the browser support.
Does anybody know that?

**Comment by jonathansampson** [comment]
@youngwind You might be looking for [Modernizr](https://github.com/modernizr/modernizr)?

**Comment by jdalton** [comment]
The `is.js` library uses `chai` as its assert library which errors in IE8 so it's safe to assume that solid support is modern browsers (current and previous browser releases) plus IE9 and up.
