### ISSUE TITLE
About the state of this project and an apology

### ISSUE THREAD

**Issue by arasatasaygin** [arasatasaygin/is.js#186]
Hey,
First of all, sorry for the absence and the inconvenience caused to you people. I mean it!
I'm right now on a SE Asia trip and not actively coding. So, I'm contacting with some friends (of friends) who I trust about collaboration opportunities. If this doesn't work out, I'll try to contact with contributors as well.
Thank you for the patience, interest and your heart.

Cheers
(⌐■_■)

**Comment by ironmaniiith** [comment]
Thanks @arasatasaygin 
If you are unable to contact some people who are willing to maintain the code, I would be more than happy to help you out.
Thanks.

**Comment by ironmaniiith** [comment]
@arasatasaygin , were you able to find anyone for maintaining is.js, I guess contributors are losing hope with this project, is this the end.?

**Comment by planttheidea** [comment]
@arasatasaygin, I volunteer my services as well. I'm already maintaining a library based on this ([isit.js](https://github.com/planttheidea/isit.js)) with various bugfixes, additional checkers, and code coverage with full unit testing. I'm happy to help out however I can.

**Comment by jt3k** [comment]
BUMP

**Comment by jt3k** [comment]
BUMP

**Comment by jonathansampson** [comment]
I'm considering making a few fixes to resolve some of the presently filed issues. Is this project going to be maintained moving forward? It looks like there are a lot of pull requests that have been ignored for a long, long time.

**Comment by jt3k** [comment]
@arasatasaygin do anything! the project dies.
give the right of control to anyone

**Comment by jdalton** [comment]
Hey y'all!

I've been given commit rights and have done a clean-up pass, pruned issues, and applied some bug fixes.

**Comment by jonathansampson** [comment]
@jdalton Uncle Buck Points!

**Comment by ironmaniiith** [comment]
Aaah, good to see the come back of is.js (with more than 50+ notifications on my mail :sweat_smile: )

**Comment by ironmaniiith** [comment]
@jdalton can you please update the gh-pages branch as well, it becomes quite handy many a times to just check things on is.js.org.

**Comment by jdalton** [comment]
I'll accept PRs to update the gh-pages 💃

**Comment by jdalton** [comment]
@ironmaniiith is now core 👏 🎉 🙌  and I have npm publish rights. Expect cutting a release soon.

**Comment by jdalton** [comment]
Things are shaping up well so I think we can call this issue closed. Thanks all!

**Comment by ironmaniiith** [comment]
Thanks :smile:

**Comment by jt3k** [comment]
Спасибо!
