### ISSUE TITLE
worker threads

### ISSUE THREAD

**Issue by soliton4** [arasatasaygin/is.js#189]
hi,
great toolset!

did you consider supporting web workers?
within the worker there is no window object. i tried to replace it with self but the detection of internet explorer for example doesnt work.

**Comment by jt3k** [comment]
project abandoned.
The creators do not have time to develop "is.js"

**Comment by soliton4** [comment]
would it be ok to do a pr?
are you maintaining is.js?

**Comment by jt3k** [comment]
many pr is not accepted for a long time :(

i am not a maintainer.

this man is a maintainer https://github.com/arasatasaygin/is.js/issues/186

**Comment by planttheidea** [comment]
@jt3k if you submit me a PR in [isit.js](https://github.com/planttheidea/isit.js) I can likely incorporate it there.
