### ISSUE TITLE
is.positive should consider 0 as positive (also, is.negative)

### ISSUE THREAD

**Issue by zazapeta** [arasatasaygin/is.js#190]
is.positive(0) return false... its weird (and wrong) : **0 is positive and negative, pur and complex**.

**Comment by ironmaniiith** [comment]
Please refer this.
https://simple.wikipedia.org/wiki/Positive_number

**Comment by zazapeta** [comment]
Sorry, but wikipedia is not THE truth .
Please, let me proof that 0 is both (positive and negative) : 
**positive :**
 let 'sqrt' the square root. In R, we cannot determinate the sqrt of a negative number. But we have : sqrt(0) = 0, so 0 is a postive number as we know the definition of a square root.
<hr>
**negative :**
 Let _x_ a number in R. 
  if x is positive we have : x * -1 = -x (negative). And if x = 0 we can write : 
   0 * -1 = 0. So, 0 is positive.
 In the same time, we can conclude that 0 is negative too. 

Regards.

**Comment by sebastialonso** [comment]
@zazapeta In a mathematical context, theorems and proofs, the non-positive includes negative reals AND zero, whatever Wikipedia says. The same goes with non-negative. Your first proof is incomplete in the sense that you have only proved that zero in non negative. Not that it is positive. Your second proof is also wrong: second line applies also to negative numbers. x * -1 = -x is valid for all x reals, regardless of its sign.
Including zero only within the positive numbers and not the negatives is not only wrong, it feels dishonest. Also, including it in both methods seems redundant (besides wrong) if you're interested in dealing with the critic case, namely 0.  For that matter, better to count with particular methods.

Incidentally, my pull request #194  includes non positive, non negative and non zero methods, trying to achieve a more precise vocabulary if you're thinking in theorems :)

**Comment by jt3k** [comment]
in mathematika posible negative and positive zero

look in source in this package https://github.com/sindresorhus/negative-zero
