### ISSUE TITLE
is.opera fails

### ISSUE THREAD

**Issue by jlettvin** [arasatasaygin/is.js#191]
navigator.userAgent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36 OPR/36.0.2130.65";

Reading your code, it looks like it should work.

**Comment by jonathansampson** [comment]
The problem with this test is that `userAgent` is converted to lower-case, but the regex doesn't contain the `i` flag to make the match case-insensitive. As such, neither *Opera* nor *OPR* are found.

**Comment by jdalton** [comment]
Dup of #130. Fixed by #197.

**Comment by jlettvin** [comment]
Thank you.

On Thu, Jun 23, 2016 at 4:57 PM, John-David Dalton <notifications@github.com
> wrote:

> Dup of #130 <https://github.com/arasatasaygin/is.js/issues/130>. Fixed by
> #197 <https://github.com/arasatasaygin/is.js/pull/197>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/arasatasaygin/is.js/issues/191#issuecomment-228181542>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABK-S9Y6hibHt07WsoPC-o4Zz5e7WDbRks5qOvNIgaJpZM4IXw0o>
> .
>



-- 
This e-mail is from Jonathan D. Lettvin, and may contain information that
is confidential or privileged. If you are not the intended recipient, do
not read, copy or distribute the e-mail or any attachments. Instead, please
notify the sender and delete the e-mail and any attachments. Thank you.

Jonathan D. Lettvin
