### ISSUE TITLE
is.uri (RFC-3986)

### ISSUE THREAD

**Issue by moooji** [arasatasaygin/is.js#196]
I have created a PR (https://github.com/arasatasaygin/is.js/pull/195) to check URIs according to RFC-3986 based on the JOI implementation.

http://www.rfc-base.org/rfc-3986.html
https://github.com/hapijs/joi

This will validate to:
```
is.uri('http://localhost') // true
is.uri('http://test.com') // true
is.uri('http://www.test.com/') // true
is.uri('http://www.test.com:8080') // true
is.uri('ftp://user:pass@com:8080') // true
is.uri('mongodb://user:pass@cluster1.test.com:8080') // true
is.uri('http://user:pass@www.test.com:8080') // true
is.uri('https://www.youtube.com/watch?v=Ex6Brmg4Jes') // true
is.uri('http://xn--80af0a3e.com/') // true

is.uri('#') // false
is.uri('test.com') // false
is.uri('www.test.com') // false
```

**Comment by jdalton** [comment]
Thanks @moooji!

We'll keep an eye on [the popularity of the request](https://github.com/arasatasaygin/is.js/blob/master/CONTRIBUTING.md#feature-requests).
