### ISSUE TITLE
Confusion with is.json

### ISSUE THREAD

**Issue by ironmaniiith** [arasatasaygin/is.js#198]
Right now, is.json behaves like this.

```javascript
is.json({});
// true

is.json({"key": "val"}); 
// true

is.json([{"key1": "val1"}, {"key2": "val2"}]);
// false
// Shouldn't it be true..?
```

Which is correct but bit confusing if one goes and check the validity of all the three objects above on any online validator.

Also if a "valid json string" is provided to is.json, it returns false.
Shouldn't it be better if we add a method to verify whether a ``string`` is a ``valid json`` or not (which is commonly verified on all the online validators)

So that,
```javascript
is.jsonString('{"key": "val"}');
// true

is.jsonString('[{"key1": "val1"}, {"key2": "val2"}]');
// true
```

Please let me know if it makes sense, I'll submit the [PR](https://github.com/ironmaniiith/is.js/commit/0a458de85a74360b29e2a27f1660d9f52b0eca54)

**Comment by jdalton** [comment]
The `is.json` method is interesting. It's just checking if the ToStringTag is of "Object". Validation of JSON strings is different enough for a new method. I imagine it would be:
```js
is.jsonString = function(string) {
  try {
    return (JSON.parse(string), true);
  } catch (e) {}
  return false;
};
```

We'll keep an eye on [the popularity of the request](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests).
