### ISSUE TITLE
Bug + improvement in is.capitalized

### ISSUE THREAD

**Issue by ironmaniiith** [arasatasaygin/is.js#199]
###### Current Implementation:
```javascript
is.capitalized = function(str) {
        if (is.not.string(str)) {
            return false;
        }
        var words = str.split(' ');
        var capitalized = [];
        for(var i = 0; i < words.length; i++) {
            capitalized.push(words[i][0] === words[i][0].toUpperCase());
        }
        return is.all.truthy.apply(null, capitalized);
    };
```

###### Description (Bug):
```javascript
is.capitalized("Hello  World");
// Results in error
```
It's because of the line
```javascript
var words = str.split(' ');
```
which results in an empty string, which further produces error when using toUpperCase()
Maybe we can use filter here to avoid empty splits.

###### Description (Improvement):
There's no point of using an extra array ```capitalized``` and checking all it's entries afterwards, instead we can just have a check inside for loop and return false.

**Comment by jdalton** [comment]
Just to clarify the bug is with strings that contain more than one consecutive space.

**Comment by jdalton** [comment]
If you're up for a PR that would rock. Don't forget to include a unit test.

**Comment by ironmaniiith** [comment]
:+1: 
Just a question, should I include the improvement mentioned as well in the same PR.?

**Comment by jdalton** [comment]
PRs are easier to reason about and merge when they're small and focused so I'd split it onto two PRs.

**Comment by jdalton** [comment]
Moved to #200.
