### ISSUE TITLE
Email Regexp is supporting turkish characters. 

### ISSUE THREAD

**Issue by zekiunal** [arasatasaygin/is.js#2]
çiş@çüş.com is validated email. is it wrong?

**Comment by arasatasaygin** [comment]
There is an extra configuration method to override your own Regexps to library.
```javascript
is.setRegexp(/your email regexp goes here/, 'email');
```
I'll also take a look at other Regexps too provide more international support.

**Comment by arasatasaygin** [comment]
According to this article, RFC 6530 supports these characters:
http://en.wikipedia.org/wiki/Email_address#Internationalization
I will keep the email Regexp for now. As I said earlier 'setRegexp' method can serve for these kind of situational issues.
Thank you.
