### ISSUE TITLE
adding is.vivaldi() support

### ISSUE THREAD

**Issue by ironmaniiith** [arasatasaygin/is.js#214]

**Comment by jdalton** [comment]
Dup of #126. Since vivaldi is built of off chromium + blink I think it's fine that it's detected as `is.chrome`.
Is.js is not intended to be the be-all-end-all of UA sniffing. There are projects like [ua-parser](https://github.com/ua-parser) for that.

**Comment by ironmaniiith** [comment]
Ok :+1:
