### ISSUE TITLE
How to use in node.js

### ISSUE THREAD

**Issue by alejandropaciotti** [arasatasaygin/is.js#22]
Could anyone tell me how to use this fantastic library in node.js?

When I using: 
```js
require ('is'); 
```
I get the error: 
```shell
Can not find module 'is_js'
```

**Comment by ryanguill** [comment]
see https://www.npmjs.com/package/is-js

add is-js to your package.json file and then ```npm install```.

**Comment by arasatasaygin** [comment]
Hey @alejandropaciotti 
You should require the module name, like this:
```javascript
var is = require('is_js');
is.number(42);
=> true
```
The package @ryanguill mentioned is not related to this repository.
This is the npm module I've published: https://www.npmjs.com/package/is_js

Sorry for the module name clutter. Unfortunately, the package name 'is' was taken.
Cheers.

**Comment by alejandropaciotti** [comment]
Wow, I installed is-js and tested it seemed perfect, then read the following comment and noticed that are similar and not just in the name.

Anyway, thank you, has been very helpful and congratulations to the creator!


Excellent idea!

**Comment by arasatasaygin** [comment]
Yeap Scotts' module looks great too. Thanks @alejandropaciotti
