### ISSUE TITLE
Suggestion: Rename setNamespace to noConflict

### ISSUE THREAD

**Issue by colindresj** [arasatasaygin/is.js#23]
It's fairly typical for methods that reset a library's namespace in order to avoid collision to be called `noConflict`. See [jQuery](https://github.com/jquery/jquery/blob/master/src/exports/global.js#L8]), [Underscore](https://github.com/jashkenas/underscore/blob/master/underscore.js#L1274), [Lodash](https://github.com/lodash/lodash/blob/master/lodash.js#L10154), [Bootstrap](https://github.com/twbs/bootstrap/blob/master/dist/js/bootstrap.js#L161), and even mainly server-side libraries like [node-uuid](https://github.com/broofa/node-uuid/blob/master/uuid.js#L240).

I think a `setNamespace` method is reserved for actually creating a new namespace on or from an object, not changing the object's current global namespace.

**Comment by arasatasaygin** [comment]
Thanks @colindresj 
You are right. Listed this one here > https://github.com/arasatasaygin/is.js/issues/44

**Comment by colindresj** [comment]
:+1:
