### ISSUE TITLE
include grunt/gulp to customize required functions

### ISSUE THREAD

**Issue by idododu** [arasatasaygin/is.js#235]
a great js library!!!

can any big one add grunt/gulp tasks to customize required functions?

eg: when u only need "enviroment" part of is.js, we can type a command "grunt only enviroment" in cmd window, and then the smaller is.js and is.min.js will be generated.

**Comment by jdalton** [comment]
Hi @idododu!

Having a modular library is a pretty nice thing. 
We'll keep an eye on [the popularity of the request](https://github.com/arasatasaygin/is.js/blob/master/CONTRIBUTING.md#feature-requests).

**Comment by ironmaniiith** [comment]
+1 in support of @idododu

**Comment by jt3k** [comment]
+1
Vote for modularity with the possibility of tree-shaking, if necessary

**Comment by joaomilho** [comment]
+10
