### ISSUE TITLE
Tests for is.dayLightSavingTime() are location dependent

### ISSUE THREAD

**Issue by tbasse** [arasatasaygin/is.js#24]
All four `is.dayLightSavingTime()` tests are failing in Australia because the given dates in the tests do not correlate with our daylight saving times over here. Should be the same for all southern hemisphere countries.

http://en.wikipedia.org/wiki/Daylight_saving_time_by_country

**Comment by arasatasaygin** [comment]
Thanks for the heads up.
Have you got any fix for this issue?

**Comment by ihopepeace** [comment]
@arasatasaygin I am working on it :)

**Comment by arasatasaygin** [comment]
:) You are like a PR machine @ihopepeace 
Thanks a lot. Cheers.

**Comment by ihopepeace** [comment]
hehe :)

**Comment by ouchxp** [comment]
Still not able to pass the time in New Zealand

**Comment by jdalton** [comment]
Closing issue as stale. Feel free to open a PR to fix the issue.
