### ISSUE TITLE
Facebook InApp Browser for iPad

### ISSUE THREAD

**Issue by IamLeTea** [arasatasaygin/is.js#247]
Hi,

I find a thing that is.mobile return true when I use iPad in Facebook InApp Browser.
(Line InApp Browser return false.)

iOS 9.3.5 & 10.0.1

**Comment by jdalton** [comment]
Hi @IamLeTea!

This appears [by design](https://github.com/arasatasaygin/is.js/blob/v0.9.0/is.js#L719-L721).

**Comment by jdalton** [comment]
Actually that's for `ipod`. Do you know what your `navigator.userAgent` value is?

**Comment by jdalton** [comment]
Looks related to http://stackoverflow.com/questions/11414006/is-this-a-facebook-for-ios-webview-user-agent.

**Comment by IamLeTea** [comment]
The navigator.userAgent is:

Mozilla/5.0 (iPad; CPU OS 10_0_1 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) Mobile/14A403 [FBAN/FBIOS;FBAV/64.0.0.43.138;FBBV/38842789;FBRV/0;FBDV/iPad4,4;FBMD/iPad;FBSN/iPhone OS;FBSV/10.0.1;FBSS/2;FBCR/;FBID/tablet;FBLC/zh_TW;FBOP/5]

**Comment by jdalton** [comment]
Thanks!

**Comment by IamLeTea** [comment]
You are welcome :)
