### ISSUE TITLE
is.ie(8) use on redhat jboss got version 7

### ISSUE THREAD

**Issue by somsak-tk** [arasatasaygin/is.js#249]
Dear is.js
    I use is.ie(8) on my app struts2 , tomcat7 run on ie 8.0.7601.17514 script work fine i got return "true".
But when i deployed on redhat jboss enterprise application platform 6.4.8 GA (jdk1.7) i run on same ie
but return is "false" then i try is.ie(7) return is "true".

thanks for any information

**Comment by jt3k** [comment]
Maybe in the second case, turn on compatibility mode in ie?
Look at [here](http://stackoverflow.com/questions/3449286/force-ie-compatibility-mode-off-using-tags) to force switch off compatability mode in ie
