### ISSUE TITLE
Compare arrays or objects by the values

### ISSUE THREAD

**Issue by ishmangit** [arasatasaygin/is.js#250]
Hi to all!,

I'm wondering if is it possible to compare two array or object variables using this library. I've tried to compare with is.equal(array1, array2), having both arrays the same values but the command returns "false" to me...

Thank you!

**Comment by jt3k** [comment]
simply but wrong and slow way is using matching like this
```
 JSON.stringify(array1) ===  JSON.stringify(array2)
```
but if u not have serializable objects this way will throw an error.

second way looks like this https://github.com/substack/node-deep-equal/blob/master/index.js and has name "deep-equal"

**Comment by jdalton** [comment]
Dup of #80.
