### ISSUE TITLE
IE 8 fallback error

### ISSUE THREAD

**Issue by RGFnaGFuIEd1bmF5** [arasatasaygin/is.js#251]
I'm getting "Expected identifier" on line 93 in IE8.

`is.arguments = function(value) {    // fallback check is for IE
        return is.not.null(value) && (toString.call(value) === '[object Arguments]' || (typeof value === 'object' && 'callee' in value));
    };`

How can i fix this.

**Comment by jdalton** [comment]
Hi @RGFnaGFuIEd1bmF5!

You need to upgrade your version of is.js.

**Comment by jdalton** [comment]
See https://github.com/arasatasaygin/is.js/commit/e6393f789efd454141b4ed15b0dfe03711b8e587.
