### ISSUE TITLE
is.chrome() false positive in Opera 41.0

### ISSUE THREAD

**Issue by Anaphase** [arasatasaygin/is.js#253]
`is.chrome()` returns `true` in Opera 41.0 (and possibly other versions, I've only tested against 41.0.2353.46.) The reason is that `navigator.vendor === "Google Inc."` and `chrome` is in the `userAgent` string.

**Comment by Anaphase** [comment]
Possible solution would be to include an `is.opera()` check in the `is.chrome()` method.

**Comment by jdalton** [comment]
Sounds good. @Anaphase are you up for making a PR?

**Comment by Anaphase** [comment]
Sure! See PR #254

**Comment by jdalton** [comment]
Moved to #254.
