### ISSUE TITLE
is.array and is.object bug

### ISSUE THREAD

**Issue by Escort42** [arasatasaygin/is.js#255]
var a = {
	"No":["1000","200"],
	"Date":"22/12/2012"
}

is.array(a["No"])
// --> true

is.object(a["No"])
// -->true   .....this should be false. because a["No"] is array ...

**Comment by jucrouzet** [comment]
In Javascript, everything except primitives (strings, numbers, bool, null, undefined) is an object, so basically, an Array **IS** an object.
