### ISSUE TITLE
unexpected behavior in regex-based checks for undefined

### ISSUE THREAD

**Issue by fluxsauce** [arasatasaygin/is.js#263]
```js
console.log(is.ip(undefined));
```

```
true
```

That threw me for a bit. The workaround is `is.existy` before `is.ip` but that seems kind of inelegant. Is this by design?

**Comment by jdalton** [comment]
Hi @fluxsauce!

Are you up for creating a PR?

**Comment by fluxsauce** [comment]
@jdalton on it. Turns out this affects anything with a regex. I've fixed it, currently updating the tests, PR tonight.

**Comment by ironmaniiith** [comment]
@fluxsauce , can you tell which browser and which version of is.js are you using?

**Comment by fluxsauce** [comment]
@ironmaniiith Node.js, I'll have to check the package version and get back to you.

**Comment by fluxsauce** [comment]
@ironmaniiith that's embarrassing, I just sandbox tested this. The version that was being used in the project was 0.7.0, I replicated the bug in 0.8.0, looks fixed in 0.9.0.

My PR did fix a bug in the tests for IPV6, though :-)

**Comment by ironmaniiith** [comment]
I can't find any bug in IPV6 as well, which bug btw?

**Comment by fluxsauce** [comment]
Hyper-minor, it was supposed to test the IPv6 validation and instead tested the IP validation which tangentially tested the IPv6 but gave a false positive because it tests IPv4 before IPv6.

https://github.com/arasatasaygin/is.js/pull/264/files#diff-c1129c8b045390789fa8ff62f2c6b4a9L593

**Comment by ironmaniiith** [comment]
Ok, so it's just in the test file.
I think we can revert back the PR as there was no issue with the previous implementation

**Comment by jdalton** [comment]
Let's keep the patch and instead add unit tests. The check is solid because it prevents `undefined` and `null` from being coerced to strings in `RegExp#test` which prevents things like `is.alphaNumeric()` from returning `true` (as it currently does in the stable release).

**Comment by fluxsauce** [comment]
> The check could possibly be restricted further to only allowing strings.

`is.existy(value) && is.string(value) && regexes[regexp].test(value)` would fulfill that. A thought, would you be open to a loop for the tests rather than having all the copy/paste logic?

**Comment by jdalton** [comment]
I went ahead and kept the `is.string` check out of it since I found unit tests allowing number values for some methods.
