### ISSUE TITLE
support to detect UCBrowser

### ISSUE THREAD

**Issue by mimani** [arasatasaygin/is.js#271]
Is there support to detect where current browser is UCBrowser?

**Comment by jdalton** [comment]
Hi @mimani!

I don't believe so.

**Comment by mimani** [comment]
Is there any plan to add this or is make sense to have similar functionality as you already have `is.chrome();`, `is.firefox();`, etc.

**Comment by jdalton** [comment]
If you create a PR we'll add it. Please include unit tests with the PR.
