### ISSUE TITLE
Adding is.prime method

### ISSUE THREAD

**Issue by mhakes** [arasatasaygin/is.js#274]
// just a suggestion..
// supports not, any, all
<pre>
is.prime = function (value) {
        var basePrimes = [2, 3, 5];
        var sqrt = 0;
        var checking = 7;
        var increment = 4;
        function mod(divisor) {
            return value % divisor === 0;
        }
        // is.all.safeInteger() would be necessary 
        // all/any functionality 
        if (!Number.isSafeInteger(value) || value < 2) {
            return false;
        }
        sqrt = Math.sqrt(value);
        if (is.inArray(value, basePrimes)) {
            return true;
        }
        if (mod(2) || mod(3) || mod(5)) {
            return false;
        }
        if (is.integer(sqrt)) {
            return false;
        }
        while (checking < sqrt) {
            if (mod(checking)) {
                return false;
            }
            checking += increment;
            increment = 6 - increment;
        }
        return true;
    };
</pre>

**Comment by ironmaniiith** [comment]
Hi @mhakes
We do not have is.prime() method currently.
We'll keep an eye on [the popularity of the request](https://github.com/arasatasaygin/is.js/blob/master/CONTRIBUTING.md#feature-requests).
