### ISSUE TITLE
is.odd(-5) should return true, but false given.

### ISSUE THREAD

**Issue by modood** [arasatasaygin/is.js#275]
as you know:
```js
console.log(-5 % 2); // output: -1
```
is.js:
```js
// is a given number odd?
is.odd = function(n) {
    return is.number(n) && n % 2 === 1;
};
```

**Comment by jdalton** [comment]
Hi @modood!

Would you be up for creating a PR?

**Comment by ironmaniiith** [comment]
@modood , if you are up for PR, I think it would be better to just check for even numbers using `n % 2 === 0` and then using `is.not.even(n)` in `is.idd`

**Comment by jdalton** [comment]
Thanks. Merged! 😀
