### ISSUE TITLE
Add is.promise

### ISSUE THREAD

**Issue by artemv** [arasatasaygin/is.js#279]
Promises are everywhere these days so looks useful.

**Comment by jdalton** [comment]
I've seen it suggested that such methods be named `is.thenable` since a promise can be anything with the `.then` contract.

**Comment by jdalton** [comment]
Moved to #280.

**Comment by bbusschots-mu** [comment]
I regularly need to check if a user has passed a promise as a parameter to a function, so it would be great to have either is.promise() or is.thenable() added to this wonderful library.

**Comment by artemv** [comment]
@bbusschots-mu it's there since https://github.com/arasatasaygin/is.js/commit/43bd1b8f87beeccd69a3f26c4a68b473830ef5b9, but the changes are not being released/tagged lately for some reason. You can include that change like this:
```
  "dependencies": {
...
    "is_js": "arasatasaygin/is.js#43bd1b8f87beeccd69a3f26c4a68b473830ef5b9",
...
}
```
