### ISSUE TITLE
Feature Request: is.operaMini()

### ISSUE THREAD

**Issue by kafeltz** [arasatasaygin/is.js#285]
Would be nice recognize the difference from these two since they have a completed different version.

Opera Mobile is version 46.
Mini Opera Mobile is version 33.

So i can't check something like this: `var isOutdated = is.mobile() && is.opera('< 46')`

**Comment by MarkelFerro** [comment]
It's a great idea.

**Comment by ironmaniiith** [comment]
Added [here](https://github.com/arasatasaygin/is.js/commit/bf6534e2877343ab6e42ed4b75de4a6935875929)

Thanks for bringing this into notce.
