### ISSUE TITLE
Ubuntu 18.04 not recognized as Linux using firefox nightly

### ISSUE THREAD

**Issue by KurozeroPB** [arasatasaygin/is.js#288]
I'm on Ubuntu 18.04 and `is.linux()` is returning false. \
I tested it on firefox nightly, firefox, chromium and chrome, on both firefox it returns false but on chromium and chrome it returns true.

**Comment by ironmaniiith** [comment]
Could you please paste the userAgent string as well for the above case?

**Comment by KurozeroPB** [comment]
It was a lot of lines so I put it in a hastebin hope that's good too. \
https://hastebin.com/gikibetuci.php

**Comment by ironmaniiith** [comment]
Thanks.
Looks like `navigator.appVersion` is not reliable anymore.

**Comment by ironmaniiith** [comment]
Fixed [here](https://github.com/arasatasaygin/is.js/commit/56294950656ba58f940248510cdf3e45af357a1e)

**Comment by KurozeroPB** [comment]
No problem, thanks for the quick fix
