### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by dackdel** [arasatasaygin/is.js#289]
It might just be me, dont get me wrong im not trying to force my design sensibilities on you but jesus christ the documentation webpage has too much scroll. 

Here is a suggestion: https://tympanus.net/codrops/2018/01/12/freebie-scribbler-website-template-html-sketch/ to make it more, readable. To save you some clicks here is a live demo (https://tympanus.net/Freebies/scribbler/)

**Comment by jdalton** [comment]
Thanks for the tip @dackdel!
