### ISSUE TITLE
Test is.ip

### ISSUE THREAD

**Issue by AlexandreAWE** [arasatasaygin/is.js#29]
It will be great if we can validate a IP adress

**Comment by ihopepeace** [comment]
I will do that today.. Thanks for suggestion :)

**Comment by chiefGui** [comment]
+1

**Comment by ihopepeace** [comment]
I have created a pull request :)

**Comment by AlexandreAWE** [comment]
Thank for this PR @ihopepeace :)

**Comment by arasatasaygin** [comment]
Merged them. Thanks for all the hard work @ihopepeace
