### ISSUE TITLE
Document how to import this lib

### ISSUE THREAD

**Issue by lmj0011** [arasatasaygin/is.js#297]
```js
import is from 'is_js'
```

```js
const is = require('is_js')
```

I don't think it's very obvious on how to import this lib into your node.js script. It wouldn't hurt to include one of the above imports in the README examples.

related issues:

https://github.com/arasatasaygin/is.js/issues/22

https://github.com/arasatasaygin/is.js/issues/158

**Comment by kafeltz** [comment]
Any package inside package.json is: **import xxx from "yyy"** it is nice to make **import xxx from "xxx
"**

**Comment by evdama** [comment]
that's done in https://github.com/evdama/is-it-check as I've forked and migrated the entire repo to ES6 now 🥳 
Have a look and send PR in case...
This one can probably be closed if you're happy with the migration...
