### ISSUE TITLE
logical && and logical ||

### ISSUE THREAD

**Issue by evdama** [arasatasaygin/is.js#303]
I was wondering if there's a is.js way to replace the `&&` with? This snippet for example

```js
if ( is.object( request.useragent ) && is.propertyDefined( request.useragent, 'isBot' ) ) {
       // both conditions are truthy
      } else {
      // at least one condition is falsy
    }
```

can't be written as
```js
if (  is.all.truthy( is.object( request.useragent )  is.propertyDefined( request.useragent, 'isBot' ) ) ) {
       // both conditions are truthy
      } else {
      // at least one condition is falsy
    }
```
or am I missing something simple here?

**Comment by ironmaniiith** [comment]
You can ofcourse use [is.truthy](https://github.com/arasatasaygin/is.js#istruthyvalueany) which supports the all interface. You can either give comma separated values to `is.all.truthy` or you can pass an array as well.

**Comment by evdama** [comment]
gosh, sure, thanks much... closing :)
