### ISSUE TITLE
is.leapYear()?

### ISSUE THREAD

**Issue by shashisp** [arasatasaygin/is.js#32]

**Comment by arasatasaygin** [comment]
Yeap, maybe.
Is this check help anyone? What do you think?

**Comment by hamid6** [comment]
Thanks Aras for this great lib.

Here is the leap year calculation taken from K&R's "The C programming language" 

// is the given year a leap year?
is.leapYear = function(year) {
    return is.number(year) && ((year % 4 == 0 && year % 100 != 0) || year % 400 == 0);
};
// leapYear method does not support 'all' and 'any' interfaces
is.leapYear.api = ['not'];

**Comment by vrunoa** [comment]
what about this implementation for getting leap year:

```javascript
// is the given year a leap year?
is.leapYear = function(year) {
    return is.number(year) && (new Date(year, 1, 29).getMonth() == 1);
};
```

Which one do you think is better ?

**Comment by arasatasaygin** [comment]
I found this specification about leap years:

In the Gregorian calendar 3 criteria must be taken into account to identify leap years:
- The year is evenly divisible by 4;
- If the year can be evenly divided by 100, it is NOT a leap year, unless;
- The year is also evenly divisible by 400. Then it is a leap year.

Implementation of @hamid6 seems pretty good. Would you like to send a PR about this issue? Changing the 'is.js' file and 'tests' is good enough. I can do the rest.
Thanks.

**Comment by vrunoa** [comment]
Testing times, @hamid6 implementation is much faster. I would go for that answer too.

**Comment by hamid6** [comment]
Thanks all, I'll make a PR.
Cheers

**Comment by arasatasaygin** [comment]
Added by @hamid6 on https://github.com/arasatasaygin/is.js/pull/53
