### ISSUE TITLE
Support version numbers for all browsers

### ISSUE THREAD

**Issue by bennyn** [arasatasaygin/is.js#39]
Hi, thanks for your great library!

I just read your documentation and found that you support checks for specific Internet Explorer versions with `is.ie(value:number)`. I was wondering why don't support the same thing for Firefox, Chrome, etc. like `is.chrome(value:number)`?

To be consistent and because it is helpful I suggest to add the version checks for all browsers as version checks become more and more important with the evolvement of new HTML5 features.

**Comment by arasatasaygin** [comment]
Thanks @bennyn 
I've implemented the most vital one for now nut as you said version support for other browsers can be very useful.

**Comment by jonathansampson** [comment]
I like this idea, but would see more value in having the ability to check boundaries. For instance, is the browser version below or above a boundary. More often than not we want to know if the version is 9 or greater, 8 or lower, etc.

**Comment by jdalton** [comment]
I've added the `version` param to the other browser methods.

Having a method to return a number or check a range would be nice but gets tricky as I believe every method currently returns a boolean so returning a number would seem out of place.

**Comment by jonathansampson** [comment]
@jdalton I agree that returning a number is not in accordance with the general pattern of is.js, but I wonder how helpful a general version check is ultimately. For internet explorer, I'd have to write the following to test for an older version:

```javascript
if ( is.ie() && !is.ie(11) && !is.ie(10) && !is.ie(9) ) {
 // You're using IE 8 or lower
}
```

Perhaps we could create a cache on the `is` object that holds relevant values?

```javascript
if ( is.ie() && is.cache.browsers.ie.version < 9 ) {
    // You're using IE 8 or lower
}
```

This way, the individual browser methods continue to return Boolean values, but only after storing relevant data on an available cache.

**Comment by jdalton** [comment]
I tackled this (https://github.com/arasatasaygin/is.js/commit/b022fabe46397d05009c97bca036298015dccafb) by adding support for version ranges to the methods. You can now do:
```js
is.edge('> 13');
is.firefox('<=45');
is.chrome('>= 51');
// as a side effect even this works
is.safari('*');
```
