### ISSUE TITLE
Tests failing with certain UK postcodes

### ISSUE THREAD

**Issue by brnrd** [arasatasaygin/is.js#4]
The regex to check if a postcode is a UK one fails with most of the postcode listed on [Wikipedia page about special UK postcodes](http://en.wikipedia.org/wiki/Postcodes_in_the_United_Kingdom#Special_cases).

**Comment by arasatasaygin** [comment]
Thanks @brnrd I'll try new RegExps to cover more. If you have suggestions, let me know.

**Comment by RaitoBezarius** [comment]
```javascript
/^[A-Z]{1,2}[0-9RCHNQ][0-9A-Z]?\s?[0-9][ABD-HJLNP-UW-Z]{2}$|^[A-Z]{2}-?[0-9]{4}$/
```
@brnrd @arasatasaygin : Should be sufficient, I think? I've tested it over the most of the postcode you've listed on the Wikipedia page. (And I've added support for whitespace in order to make it more convenient : ASCN 1ZZ works like ASCN1ZZ).

**Comment by arasatasaygin** [comment]
Thanks @RaitoBezarius 
It works great. Updated it with this one.
