### ISSUE TITLE
is.chrome(value:number).orLater()

### ISSUE THREAD

**Issue by bennyn** [arasatasaygin/is.js#40]
In some of my projects I need to check if a browser has at least a specific version. It would be great if I could use `is.js` for that purpose.

So I would like to have a function that returns `true` if a browser version is greater than or equal to a given number. Like: `is.ie(8).orLater()`. Same goes for other browsers like Chrome, Firefox, etc.

**Comment by njenia** [comment]
I created a pull request #71 for this. Tell me what you think.

**Comment by lipis** [comment]
+1

**Comment by jdalton** [comment]
Moved to #71.
