### ISSUE TITLE
Checking file extensions?

### ISSUE THREAD

**Issue by vrunoa** [arasatasaygin/is.js#42]
Hey @arasatasaygin what do you think about adding some methods to check file extensions? 
like: ``` is.image``` ```is.pdf``` ```is.excel``` ```is.extension``` 

I'll implement ```is.image``` tomorrow

**Comment by arasatasaygin** [comment]
Thanks @vrunoa 
I think they can be handy. Can these checks help anyone beside me?

**Comment by julienbrunuk** [comment]
Yes, definitely! How about also checking against a MIME Type?

**Comment by vrunoa** [comment]
I made a first implementation to check image extension
```javascript
is.extension = {};
is.extension.image = function(name) {
  var extensions = [/\.png$/,/\.jpg$/,/\.jpeg$/,/\.gif$/];
  return is.string(name) 
    && extensions.some(function(el){ return el.test(name) });
}
```
[https://github.com/Urucas/is.js/blob/master/is.js#L798-L804](https://github.com/Urucas/is.js/blob/master/is.js#L798-L804)

What do you think?

**Comment by fslone** [comment]
On this wouldn't you want the image extension regex check to be case insensitive?

**Comment by vrunoa** [comment]
Yeah @fslone , good point, I miss this. This weekend i'll make an update.

**Comment by fslone** [comment]
@vrunoa No need, I already made it case insensitive in my forked repo and fixed a few other typos so I'll submit a pull request tomorrow. I've also added ~150 is.extension methods to check various file types like is.extension.doc, is.extension.xls, etc. Do you think this would be something worth submitting a pull request for? If so I'll include that in my request as well.
