### ISSUE TITLE
Under is not the opposite of Above

### ISSUE THREAD

**Issue by tbasse** [arasatasaygin/is.js#43]
First of all, excuse me in advance if I'm very picky here but the naming of the `is.above()` and `is.under()` methods are really bothering me. It really should be above/below or over/under but definitely not abover/under :)

Maybe just rename `is.under()` to `is.below()` and alias those methods to `is.over()` and `is.under()`.

Again, I might be very picky here but the current naming just looks very odd.

**Comment by arasatasaygin** [comment]
Nope, you are noy picky @tbasse 
My English just sucks. Thanks for the suggestion.

**Comment by arasatasaygin** [comment]
Listed this suggestion here > https://github.com/arasatasaygin/is.js/issues/44
Thanks.
