### ISSUE TITLE
Make is.dateString(value:any) match date with scores (and validate?)

### ISSUE THREAD

**Issue by iruy** [arasatasaygin/is.js#45]
From my side I just added a new regex like:
>dateString_scored: /^(1[0-2]|0?[1-9])\-(3[01]|[12][0-9]|0?[1-9])\-(?:[0-9]{2})?[0-9]{2}$/,

to the regex list. Would it be possible to add validation for impossible date like 12/34/5678?

**Comment by njenia** [comment]
I think that score-delimited dates are not that common, hence it shouldn't be built-in to the library.
I saw that aras (the author) is planning to provide a way to add your RegExps to the lib on the fly (and not only replace existing ones like you can do today). #15 
About the impossible date check - the dateString RegExp check does exactly what you are looking for :)

**Comment by jdalton** [comment]
Thanks!

We'll keep an eye on [the popularity of the request](https://github.com/arasatasaygin/is.js/blob/master/CONTRIBUTING.md#feature-requests).
