### ISSUE TITLE
Is it possible to add it in angularjs?

### ISSUE THREAD

**Issue by michele-prandina** [arasatasaygin/is.js#50]
I wonder if it can be implemented in angular js eg:
```javascript
angular.controller('Ctrl', ['$scope', '$isJs', function($scope, $isJs){
 if($scope.someModel.is.Something()) {
  doSomething; 
 }
}]);
```

**Comment by leosilvano** [comment]
i guess you can, just create a module named isJS and load the script over there

**Comment by arasatasaygin** [comment]
I'm not fluent in AngularJS but as @leosilvano said it seems possible.
Create a module. Then create your 'is' factory from exposed 'is' object to inject later on your controllers:
```javascript
yourIsModule.factory('is', function() {
    return window.is; // is.js must already be loaded on the page
});
```
Let me know if you have any problems @michele-prandina 
Cheers

**Comment by omer-demir** [comment]
@michele-prandina in codepen i made demo for usage. Either you can create module for library or create service in your application module. It depends on your need.
http://codepen.io/omer-demir/pen/RNjYaW

or the code block is like

```javascript 
var isModule=angular.module('isModule',[]).factory('isService',function($window){
  return $window.is;
});
```
