### ISSUE TITLE
Implementation of is.undefined? 

### ISSUE THREAD

**Issue by umayr** [arasatasaygin/is.js#56]
Hello, there. 

Is there a reason you used `value === void 0;` to check if value is undefined rather than `typeof value === 'undefined'`?

Thanks for the awesome library, btw.

**Comment by omer-demir** [comment]
As far as i know using ```value===void 0;``` is more efficient than ```typeof value==='undefined'``` or ```value===undefined```

**Comment by arasatasaygin** [comment]
:+1: @omer-demir 
`undefined` is a permissible variable name, so you can assign a new value to it.
`void` takes any value and returns `undefined` always. It's a convention to give `0` for `void' though.
