### ISSUE TITLE
FEATURE - can you add an 'is.inArray()' check?

### ISSUE THREAD

**Issue by BrockBeldham** [arasatasaygin/is.js#6]
For example if I have an item and I want to check to see if it's in an array I have:

    is.inArray([1, 2, 3, 4, 5, 6], 2);
    => true
    
    is.not.inArray([1, 2, 3, 4, 5, 6], 10);
    => true

Theoretically you could also do 'is.inObject()' or even 'is.inString()'.

**Comment by arasatasaygin** [comment]
Thank for the feature offer @BrockBeldham 
is.inArray check added by ryantemple right now.

For strings you can use:
```javascript
is.include('Some text goes here', 'text');
=> true
is.include('test', 'text');
=> false
is.not.include('test', 'text');
=> true
```

and for objects there is:
```javascript
is.propertyDefined({yeap: 'yeap'}, 'yeap');
=> true
is.propertyDefined({yeap: 'yeap'}, 'nope');
=> false
is.not.propertyDefined({}, 'nope');
=> true
```

Cheers.
