### ISSUE TITLE
Not working on IE 9 browser

### ISSUE THREAD

**Issue by Guru107** [arasatasaygin/is.js#63]
I tried using is.js in IE 9. But it seems to have an error in it.
![Error Screenshot] (https://raw.githubusercontent.com/Guru107/images/master/is_js_bug.png)

**Comment by Guru107** [comment]
I looked into the matter. The issue is caused because of the naming of 2 functions in the library. ```is.null()``` and ```is.function()``` . Since ```null and function``` are JavaScript keywords IE9 was throwing an error. <b>I renamed these two functions in my local copy  and its working fine</b>. The name change of these two functions can be taken up as suggested in Issue #44 .

**Comment by arasatasaygin** [comment]
I've tested it on IE9, Win7 @Guru107 
It seems fine. Is there anybody having the same issue?

**Comment by Guru107** [comment]
Hey @arasatasaygin. I figured out what was the issue. My IE had default document mode as Quirks Mode  http://en.wikipedia.org/wiki/Quirks_mode. I changed it to IE9 Standards now its working fine. However it won't work if I change it to IE7 or IE8 Standards (doesn't matter now i guess :smile: ). 
![IE9 Standard](https://raw.githubusercontent.com/Guru107/images/master/is_js_quirks_mode.png)

**Comment by Guru107** [comment]
Hey @arasatasaygin  I found out what was the problem. My IE9 Document Mode was set to Quirks Mode (http://en.wikipedia.org/wiki/Quirks_mode) by default. I have changed it to IE9 Standards now its working fine . Any how it won't work on IE7 or IE8 (doesn't matter i guess! :smile: ) 
![IE9_Standards] (https://raw.githubusercontent.com/Guru107/images/master/is_js_ie9.png)

**Comment by chiefGui** [comment]
@Guru107 @arasatasaygin I think it's important to mention browser support.

**Comment by Guru107** [comment]
@arasatasaygin @chiefGui  Adding `<!DOCTYPE html>` would set the document mode to IE9 Standards by default on IE9 browser.Ignoring to add this would result in setting of Document Mode  as <a href="http://en.wikipedia.org/wiki/Quirks_mode">Quirks  Mode</a> by default resulting in an error.

**Comment by jdalton** [comment]
Fixed by https://github.com/arasatasaygin/is.js/commit/e6393f789efd454141b4ed15b0dfe03711b8e587.
