### ISSUE TITLE
typeof NaN is 'number'

### ISSUE THREAD

**Issue by chenxianliang** [arasatasaygin/is.js#72]
// is a given value number?
    is.number = function(value) {
        return toString.call(value) === '[object Number]';
    };
   should be 
    is.number = function(value) {
        return toString.call(value) === '[object Number]' && !isNaN(value);
    };   
  ???

**Comment by arasatasaygin** [comment]
Type of NaN is number.
What others think? Should we return false for NaN on this check?

Thanks @chenxianliang

**Comment by cfj** [comment]
`NaN` may technically be a number but I don't think it's in the spirit of the `is.number` function to return true on `NaN`.

**Comment by limichange** [comment]
Don't need to change. Type of NaN is number.

**Comment by Joshua-F** [comment]
I agree with @cfj. NaN stands for Not a Number so I say keep it how it is now.

**Comment by cakuki** [comment]
@Joshua-F you do not agree with @cfj. Type of `NaN` is Number, and right now `is.number(NaN)` returns true.

:+1: for change, `is.number(NaN)` should return false.

**Comment by Joshua-F** [comment]
@cakuki, he says he doesn't think it's in the spirit of the `is.number` function, which I agree with. But to clarify , `is.number(NaN)` should return false.

**Comment by arasatasaygin** [comment]
Fixed with https://github.com/arasatasaygin/is.js/pull/79 from @jonhester 
Thanks for all the feedbacks. This check returns false for NaN right now.
