### ISSUE TITLE
MeteorJS support

### ISSUE THREAD

**Issue by rodrigok** [arasatasaygin/is.js#74]
What do you think about publish this awesome package into MeteorJS's ecosystem?

http://atmospherejs.com

**Comment by arasatasaygin** [comment]
Why not? Is there any Meteor hackers beside @rodrigok here?
What do you think about atmosphere support?

**Comment by rodrigok** [comment]
:( seems that nobody use Meteor here

**Comment by jlabresh1** [comment]
Please add to Meteor! (i just found this today, super cool library!)

**Comment by xumx** [comment]
I will give it a shot.

**Comment by rodrigok** [comment]
I can help you if you need

**Comment by xumx** [comment]
I've published it to
https://atmospherejs.com/isjs/is

To make it automatically rebuild when is.js updates to a new version. I neeed @arasatasaygin  to add a webhook to this repository 
[Here is the guide](https://github.com/MeteorPackaging/autopublish.meteor.com/wiki/How-to-manually-set-up-web-hooks)
