### ISSUE TITLE
is.space - text is all white space characters

### ISSUE THREAD

**Issue by OguzhanE** [arasatasaygin/is.js#77]
i tried to check if a the given value is all white space characters.
is.space('&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;') is currently returning false
i think, it should return true
or
implementation another new method  called `is.whitespace`

**Comment by jonhester** [comment]
How about a new method named ```is.blank```?

**Comment by arasatasaygin** [comment]
Yeap, the current implementation is returning false @OguzhanE 
What others think about the expected behaviour of this check or a new check for this one?

**Comment by jonhester** [comment]
@arasatasaygin ```is.space('      ')``` makes sense to me to return false since it's actually multiple spaces, and not just one. Changing it could cause problems for anyone currently using it to check for just a single space character.

**Comment by jonhester** [comment]
I updated the existing is.empty function to return true for strings composed of only white space. Thoughts?

**Comment by cfenzo** [comment]
@jonhester well, `' '` is by definition not empty, it contains whitespace.
My vote is for a new check, `is.whitespace`, and leave both `is.space` and `is.empty` as is.

**Comment by jonhester** [comment]
@cfenzo I agree. I'll submit a new pull request tonight.

**Comment by jdalton** [comment]
Thanks!

We'll keep an eye on [the popularity of the request](https://github.com/arasatasaygin/is.js/blob/master/CONTRIBUTING.md#feature-requests).

**Comment by jt3k** [comment]
is.blank  looks good for `/^\s+$/`

**Comment by RobDesideri** [comment]
For now, a workaround can be `is.empty(mystring.trim())`.

> Whitespace in this context is all the whitespace characters (space, tab, no-break space, etc.) and all the line terminator characters (LF, CR, etc.). - [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trim)
