### ISSUE TITLE
is.touchDevice(): possible improvement

### ISSUE THREAD

**Issue by bbak** [arasatasaygin/is.js#90]
Hi, I've seen quite a few posts somewhere else including these checks:
|| (navigator.MaxTouchPoints > 0)
      || (navigator.msMaxTouchPoints > 0))

Like here: http://ctrlq.org/code/19616-detect-touch-screen-javascript
and here: https://coderwall.com/p/mqd6pw/detect-touchcapability-in-javascript

Should they be added?

**Comment by jdalton** [comment]
Thanks!

We'll keep an eye on [the popularity of the request](https://github.com/arasatasaygin/is.js/blob/master/CONTRIBUTING.md#feature-requests).
