### ISSUE TITLE
feature request: setDate

### ISSUE THREAD

**Issue by thecotne** [arasatasaygin/is.js#92]

**Comment by jonhester** [comment]
As is.js is a checks library, I'm not sure how this makes sense. What would this be used for?

**Comment by thecotne** [comment]
for example is.past checks for date against current date 
but what if i want to check against some other date
same for all date related functions

**Comment by jonhester** [comment]
This still doesn't make sense to me since all the checks are currently static methods. You could just use ```is.inDateRange``` for special cases like what you mentioned.

**Comment by arasatasaygin** [comment]
Hey @thecotne thanks for the feature request.
Can you share a code snippet and the case you want to use it? I couldn't understand the feature or maybe we can find a solution for your case with current methods like @jonhester mentioned.
