### ISSUE TITLE
Include not working with me?

### ISSUE THREAD

**Issue by alexisohayon** [arasatasaygin/is.js#93]
Your example of is.include is not working with me (Chrome 41).
![capture d ecran 2015-03-20 a 14 33 44](https://cloud.githubusercontent.com/assets/781456/6752378/430b49b8-cf0e-11e4-9c8d-430dfe5ac04b.png)

Any idea?

**Comment by codemonkey800** [comment]
I just ran the tests for the library and `is.include` and `is.not.include` fails for me. I'll try and take a look at it.

**Comment by codemonkey800** [comment]
Alrighty. The problem had to do with the `String.prototype.includes()` method from ES6 Strings. I removed it and hopefully it gets merged in.

**Comment by arasatasaygin** [comment]
Fixed it thanks to @codemonkey800

**Comment by alexisohayon** [comment]
Thx dude, very effective! :)

Envoyé de mon iPhone
